### ISSUE TITLE
Is it possible to provide the output as an API?

### ISSUE THREAD

**Issue by NimaAra** [mattwarren/GCVisualisation#4]
First of all what a brilliant solution for a very complicated problem. Thank you for making this publicly available.

I have two questions:
- I like the way you are visualizing the data to the `Console`, would it be possible to make the output (as raw text or even better as JSON) available via an API? Possible use-case would be to call this on the server without having to resort to running it as a `Console` app or executing it as a process.
- What is the impact of listening to the `GC` events on the app (want to know the impact on our production apps)?

Thank you

**Comment by mattwarren** [comment]
Glad you like the visualisation, it was fun to put it together.

> I like the way you are visualizing the data to the Console, would it be possible to make the output (as raw text or even better as JSON) available via an API? Possible use-case would be to call this on the server without having to resort to running it as a Console app or executing it as a process.

For this I would recommend that you just work with the underlying events directly and make your own application that publishes the data as you need it. My app is tailored to the console, so extending it to an API doesn't make much sense when you can just as easily work with the [TraveEvent library](https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.TraceEvent) directly.

Feel free to take any of my code and use it as you want and post further questions if anything doesn't make sense.

> What is the impact of listening to the GC events on the app (want to know the impact on our production apps)?

The GC events are actually implemented using ETW Events, from [About Event Tracing](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363668%28v=vs.85%29.aspx):

> Event Tracing for Windows (ETW) is an efficient kernel-level tracing facility that lets you log kernel or application-defined events to a log file. You can consume the events in real time or from a log file and use them to debug an application or to determine where performance issues are occurring in the application.
> ETW lets you enable or disable event tracing dynamically, allowing you to perform detailed tracing **in a production environment** without requiring computer or application restarts.

So it seems that Microsoft designed ETW events to be used in production, but I would recommend that you do your own testing first, before turning them on in a live system!

**Comment by NimaAra** [comment]
Gotcha! Thank you.
